spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:17687/railway
spring.datasource.username=root
spring.datasource.password=SlXgnyVZP xSVbuBJcbhwziimMkQSHQZS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
