spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:17687/railway
spring.datasource.username=root
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
server.port=8080
